### ISSUE TITLE
support per-pod ssh credential override

### ISSUE THREAD

**Issue by travisghansen** [agoda-com/macOS-vz-kubelet#18]
# Feature request

## Type

- [ ] - Enhancement - completely new feature
- [X] - Improvement - make what we have better

## Is your feature request related to a problem?

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

We have different groups building different images with different needs/desires for user account naming.

## Describe the solution you'd like

> A clear and concise description of what you want to happen.

 I would like to be able to set the ssh creds on a per-pod basis by setting an annotation/label with the username and password to be used *for that pod* and overriding the defaults as set by the corresponding env vars.

## Additional context

> Add any other context or screenshots about the feature request here.

**Comment by tomekjarosik** [comment]
What about using something like this:
```
  containers:
    - name: macos-container
      image: ghcr.io/macvmio/macos-sonoma:14.5-agent-v1.6
      imagePullPolicy: IfNotPresent
      # This secret should contain SSH credentials (user/password)
      # that allow Kubernetes to execute commands inside the VM.
      envFrom:
        - secretRef:
            name: fugaci-ssh-secret
```
This would be secret provided by kubernetes "secretRef" and my understanding is that its access can be limited to kubernetes namespace and it's (kind of) secure way of connecting. For example, only team with access to kubernetes namespace and to macOS VM would be able to access this pod or image.

(sample implementation here: https://github.com/macvmio/fugaci/blob/main/pkg/fugaci/vm.go#L155 )  (there is no concept of default creds there, all pods definitions must provide them)
