### ISSUE TITLE
make snapshot fails with `error=failed to find files to archive:`

### ISSUE THREAD

**Issue by totallyGreg** [agoda-com/macOS-vz-kubelet#2]
```shell

make snapshot
  • archives
    • creating                                       archive=build/MacOSVK_1.0.0-SNAPSHOT-d03a48a_darwin_arm64.zip
  ⨯ release failed after 8s                  error=failed to find files to archive: globbing failed for pattern build/MacOSVK_darwin_arm64/MacOSVK.app: matching "./build/MacOSVK_darwin_arm64/MacOSVK.app": file does not exist
make: *** [snapshot] Error 1
```

the `.goreleaser.yml` generated file `build/config.yaml` defines an archive with source file that does not match the actual target name `MacOSVK_darwin_arm64_v8.0`

```yaml
builds:
  - id: MacOSVK
    targets:
      - darwin_arm64_v8.0

archives:
  - id: default
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format: zip
    files:
      - src: LICENSE
      - src: build/MacOSVK_darwin_arm64/MacOSVK.app
        dst: MacOSVK.app
```
modifying `.goreleaser.yml` fixes this.  

`      - src: build/MacOSVK_darwin_arm64_v8.0/MacOSVK.app`
